import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Login from '@/components/Login';
import Profile from '@/components/Profile';
import Logout from '@/components/Logout';
import { getXataClient, Cars } from '../xata';
import Image from 'next/image';

const xata = getXataClient();

export const getServerSideProps = async () => {
    const records: Cars[] = await xata.db.cars
        .select(['*', 'seller.*', 'image.*'])
        .getMany();
    return {
        props: {
            records: JSON.parse(JSON.stringify(records))
        }
    };
};

export default function Home({ records }: { records: Cars[] }) {
    console.log(records);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                {records.map((props: Cars) => {
                    return (
                        <div key={props.id}>
                            <p>{props.make}</p>
                            <p>{props.image?.url}</p>
                            {props.image?.url ? (
                                <Image src={props.image?.url} alt={props.id} />
                            ) : (
                                <p>No Image</p>
                            )}
                        </div>
                    );
                })}
                <Login />
                <Logout />
                <Profile />
            </main>
        </>
    );
}
